version: "3.7"

services:
  db:
    container_name: ${PROJECT_NAME:-openimis}-db
    image: ghcr.io/openimis/openimis-pgsql:${DB_TAG:-develop}
    environment:
      - POSTGRES_PASSWORD=$PSQL_DB_PASSWORD
      - POSTGRES_DB=$PSQL_DB_NAME
      - POSTGRES_USER=$PSQL_DB_USER
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', "$PSQL_DB_USER", '-d', "test_imis"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - database:/var/lib/postgresql/data
    restart: always
    ports:
      - 5432:5432
  db-mssql:
    container_name: ${PROJECT_NAME:-openimis}-mssql
    image: ghcr.io/openimis/openimis-mssql:${DB_TAG:-latest}
    restart: always
    environment:
      - DB_PASSWORD=$MSSQL_DB_PASSWORD
      - SA_PASSWORD=$MSSQL_DB_PASSWORD
      - DB_NAME=$MSSQL_DB_NAME
      - DB_USER=$MSSQL_DB_USER
      - ACCEPT_EULA=Y
      - DEMO_DATASET=true
    healthcheck:
      test: "bash /app/healthcheck.sh"
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 100s
    volumes:
      - database-mssql:/var/opt/mssql/data
    ports:
      - 1433:1433
  opensearch:
    container_name: ${PROJECT_NAME:-openimis}-opensearch
    image: opensearchproject/opensearch:latest
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "DISABLE_SECURITY_PLUGIN=true"  # Pour un développement local, sécurité désactiver
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    ports:
      - "9200:9200"
      - "9600:9600"
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
  opensearch-dashboards:
    container_name: ${PROJECT_NAME:-openimis}-opensearch-dashboards
    image: opensearchproject/opensearch-dashboards:latest
    ports:
      - "5601:5601"
    environment:
      OPENSEARCH_HOSTS: '["http://host.docker.internal:9200"]'
      #'["http://opensearch:9200"]'
      DISABLE_SECURITY_DASHBOARDS_PLUGIN: "true"  # correspondre à la configuration OpenSearch
      #SERVER_BASEPATH: "/kibana"
      #SERVER_REWRITEBASEPATH: "true"
      #SERVER_HOSTNAME: "0.0.0.0"
      #SERVER_CORS_ALLOW_ORIGIN: "http://localhost:8000"
    depends_on:
      - opensearch
volumes:
  database:
  database-mssql:
  opensearch-data:

